apiVersion: v1
kind: Secret
metadata:
  name: oidc
type: Opaque
stringData:
  PROVIDERS_OIDC_CLIENT_SECRET: <client-secret-from-provider>
  # Randomly generated value, change this
  SECRET: LeXrLG2Okzc7vwVeVjnRv54fQOrtzmsg
